matrix:
  - language: python
    python:
        - 3.6
    install:
        - pip install pogcli pywebview pyyaml
        - pip install --upgrade coveralls
    script:
        - coverage run -m unittest
    after_success:
        - coveralls

  - language: python
    python:
        - 3.7
    install:
        - pip install pogcli pywebview pyyaml
        - pip install --upgrade coveralls
    script:
        - coverage run -m unittest
    after_success:
        - coveralls

  - language: python
    python:
        - 3.8
    install:
        - pip install pogcli pywebview pyyaml
        - pip install --upgrade coveralls
    script:
        - coverage run -m unittest
    after_success:
        - coveralls

  - language: node_js
    node_js:
        - 10
    install:
        - npm install -g qunit node-qunit-phantomjs
    script:
        - node-qunit-phantomjs js_tests/tests.html
