matrix:
  - language: python
    python:
        - 3.6
        - 3.7
        - 3.8
        - pypy3
    install:
        - pip install -r requirements
        - pip install --upgrade coveralls
    script:
        - coverage run -m unittest
    after_success:
        - coveralls

  - language: node_js
    node_js:
        - 7
    install:
        - npm install -g qunit node-qunit-phantomjs
    script:
        - node-qunit-phantomjs js_tests/tests.html
